# SPDX-License-Identifier: GPL-2.0+

ca55_stl-objs += a55_stl.o
ca55_stl-objs += a55_stl_core_p001.o
ca55_stl-objs += a55_stl_core_p002.o
ca55_stl-objs += a55_stl_core_p003.o
ca55_stl-objs += a55_stl_core_p004.o
ca55_stl-objs += a55_stl_core_p005.o
ca55_stl-objs += a55_stl_core_p006.o
ca55_stl-objs += a55_stl_core_p007.o
ca55_stl-objs += a55_stl_core_p008.o
ca55_stl-objs += a55_stl_core_p009.o
ca55_stl-objs += a55_stl_core_p010.o
ca55_stl-objs += a55_stl_core_p011.o
ca55_stl-objs += a55_stl_core_p012.o
ca55_stl-objs += a55_stl_core_p013.o
ca55_stl-objs += a55_stl_core_p014.o

CFLAGS_a55_stl_core_p011.o += -march=armv8.5-a+crc

obj-y := ca55_stl.o
