# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#

obj-$(CONFIG_CLK_LAGUNA) += soc_clk.o
soc_clk-objs += clk-mux.o clk-gate.o clk-divider.o
soc_clk-objs += clk-pll.o
