
# SPDX-License-Identifier: GPL-2.0+
obj-$(CONFIG_AXERA_FUSA_SUPPORT)    += fusa/
obj-$(CONFIG_SUBSYS_CONTROLLER)     += glbcon/
obj-y                               += bus_iso/
obj-y                               += hwinfo/
